Tesis_01/ProjectDjango/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('visualGraph/', include('tesisForm.urls')),
    path('admin/', admin.site.urls),
    path('visualGraph/', include('django.contrib.auth.urls')),


]

Tesis_01/tesisForm/urls.py
from . import views
from django.urls import path
app_name='tesisForm'
urlpatterns = [

    path('', views.presentacion, name='presentacion'),
    path('ingresar/', views.autenticacion, name='autenticacion'),
    path('server/', views.defConsulta, name='desarrollo'),
    path('visualizacion/', views.visualizacion, name='visualizacion'),
    path('prueba1/', views.eliminarDB, name='prueba1'),
    path('prueba2/', views.eliminarConsulta, name='prueba2'),
    path('signUp/', views.SignUp.as_view(), name='signUp'),

]

Tesis_01/tesisForm/models.py
import datetime

from django.db import models
from django.conf import settings





class usuarioBaseF(models.Model):
    nombreDB = models.CharField(max_length=250)
    host = models.CharField(max_length=250)
    user = models.CharField(max_length=250)
    password = models.CharField(max_length=250)
    userConect=models.ForeignKey(settings.AUTH_USER_MODEL,default=1,on_delete=models.CASCADE)

    def __str__(self):
       return '%s %s %s' % (self.nombreDB,self.host, self.userConect)


class traversalsUSer(models.Model):
    traversal = models.CharField(max_length=550)
    baseConect=models.ForeignKey(usuarioBaseF,on_delete=models.CASCADE)
    userConect=models.ForeignKey(settings.AUTH_USER_MODEL,default=1,on_delete=models.CASCADE)
    def __str__(self):
        return '%s %s %s' % (self.traversal,self.baseConect, self.userConect)

Tesis_01/tesisForm/forms.py
from django import forms

class ConectDatabase(forms.Form):
    serverIp= forms.CharField(label="Base de datos",max_length=20)
    user=forms.CharField(label="Usuario",max_length=10)
    password = forms.CharField(label="PAssyAmor", max_length=20)

Tesis_01/tesisForm/views.py
from django.shortcuts import render, redirect
import json
from proyeccionesM import namesOfNodes,namesOfRelationships,graphSchema,traversalFunction2
from django.http import HttpResponse
from .models import usuarioBaseF,traversalsUSer
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from tesisForm.form import DBForm


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'tesisForm/signup.html'


#****************************************************************************************************************

def presentacion(request):
    authyu=request.user.is_authenticated
    if request.user.is_authenticated:
        return redirect("ingresar/")
    else:
        return render(request, 'tesisForm/presentacion.html')




@login_required()
def autenticacion(request):
    form= DBForm(request.POST)


    DBusuario = usuarioBaseF.objects.filter(userConect=request.user)

    return render(request,'tesisForm/autenticacion.html',{'form2':form,'datosUser': DBusuario})




@login_required()
def defConsulta(request):

    usuarioExiste = usuarioBaseF.objects.filter(host=request.POST['servidor'], userConect=request.user,nombreDB=request.POST['nombreDB']).exists()

    baseNuev = usuarioBaseF(host=request.POST['servidor'], user=request.POST['user'],password=request.POST['pwd1'], userConect=request.user, nombreDB=request.POST['nombreDB'])

    if usuarioExiste==False:
        print('hello')
        baseNuev.save()

    server = request.POST['servidor']
    user= request.POST['user']
    pwd=  request.POST['pwd1']
    request.session['baseNeoUser']=user
    request.session['baseNeoServer']=server
    request.session['baseNeoPwd'] = pwd


    nombreBase= request.POST['nombreDB']
    node_list=namesOfNodes(server,user,pwd)
    relation_list = namesOfRelationships(server, user, pwd)

    schemaG= graphSchema(server,user,pwd)
    schemaG1=json.dumps(schemaG[1])
    schemaG2 = json.dumps(schemaG[2])
    schemaG3 = json.dumps(schemaG[3])
    node_listSq=json.dumps(node_list)
    baseActiva1 = usuarioBaseF.objects.filter(userConect=request.user,nombreDB=nombreBase,host=str(server).strip()).first()
    traversalsAlmace = traversalsUSer.objects.filter(userConect=request.user,baseConect=baseActiva1)

    return render(request, 'tesisForm/desarrollo.html',{'node_list':node_list,'relation_list':relation_list,'schemaG1':schemaG1, 'schemaG2':schemaG2, 'schemaG3':schemaG3, 'node_listSq':node_listSq,'traveUser':traversalsAlmace})



@login_required()
def visualizacion(request):

    neoUser=request.session.get('baseNeoUser')
    neoServer = request.session.get('baseNeoServer')
    neoPwd = request.session.get('baseNeoPwd')
    #print(neoUser,neoServer,neoPwd)

    traversal = request.POST['traversal']

    baseActiva1 = usuarioBaseF.objects.filter(userConect=request.user,host=str(neoServer).strip()).first()


    travExiste = traversalsUSer.objects.filter(traversal=request.POST['traversal'], userConect=request.user,baseConect=baseActiva1).exists()

    travNuev = traversalsUSer(traversal=request.POST['traversal'], baseConect=baseActiva1, userConect=request.user)

    if travExiste==False:
        travNuev.save()

    nombreA=request.POST['nombreA']
    limit= request.POST['limit1']
    btwns = request.POST['btwns']
    degree = request.POST['degree']
    pgRk = request.POST['pgRk']

    fnLogic = request.POST['esFormula']

    datosSigma = traversalFunction2(neoServer, neoUser, neoPwd, traversal, nombreA, limit,btwns,degree,pgRk,fnLogic)

    dNOrigen=json.dumps(datosSigma[1])
    nOrigen = json.dumps(datosSigma[3])
    nDestino = json.dumps(datosSigma[4])
    nodosProp = json.dumps(datosSigma[2])

    #print(nDestino)


    return render(request, 'tesisForm/visualizacion.html',{'nombreA':nombreA,'dNOrigen':dNOrigen,'nOrigen':nOrigen,'nDestino':nDestino, 'nodosProp':nodosProp})

def eliminarDB(request):
    nombreDB=request.POST['nombreDBT']
    host=request.POST['hostT']

    baseActiva1 = usuarioBaseF.objects.filter(userConect=request.user, host=str(host).strip(),nombreDB=nombreDB).delete()
    return HttpResponse("OK")



def eliminarConsulta(request):
    traversalAlm = request.POST['travAlm']
    traversalX = traversalsUSer.objects.filter(userConect=request.user,traversal=traversalAlm).delete()

    return HttpResponse("OK")

Tesis_01/tesisForm/templates/tesisForm/autenticacion.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=0.7, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>visualGraph</title>

  <!-- Bootstrap core CSS -->
  {% load static %}
  <link href="{% static 'tesisForm/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->

  <link href="{% static 'tesisForm/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet'
    type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  {% load static %}
  <link href="{% static 'tesisForm/css/agency.min.css' %}" rel="stylesheet">


  {% load static %}
  <link href="{% static 'tesisForm/css/agency.min.css' %}" rel="stylesheet">

  <style>
    .sesionColor {
      color: darkgoldenrod;
    }
  </style>
</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">visualGraph</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
        data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
        aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>


      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav  ml-auto">


          <li class="nav-item text-uppercase">
            <a class="nav-link js-scroll-trigger" href="#about">Bases Almacenadas</a>
          </li>

          <li class="nav-item text-uppercase">
            <a class="nav-link js-scroll-trigger" href="#contact">Conectarse! </a>
          </li>
          <li class="nav-item text-uppercase">
            <a class="nav-link js-scroll-trigger"></a>
          </li>



          <li class="nav-item">
            <div class="row">
              <p class="sesionColor ">Hola, {{request.user.username}} </p>
            </div>

          </li>

          <li class="nav-item">
            <div class="row">
              <p></p>
              <br>
            </div>
            <div class="row text-uppercase">
              <a href="{% url 'logout' %}" id="botonTer">cerrar sesión</a>


            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Header -->
  <header class="masthead">
    <lldiv class="container">
      <div class="intro-text">
        <div class="intro-lead-in">Bienvenido a visualGraph!</div>
        <div class="intro-heading text-uppercase">herramienta para análisis y visualización de datos basados en grafo

        </div>
  </header>





  <!-- About -->
  <section id="about">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading text-uppercase">Registros de bases de datos almacenadas:</h2>
          <h3 class="section-subheading text-muted">Selecciona una base a la que hayas accedido o ingresa las credenciales solicitadas.</h3>
        </div>
      </div>
      <div class="row col-lg-10 offset-lg-2">
        {%for artic in datosUser%}
     
          <div class="UserDB{{ forloop.counter }} col-lg-5">
            <ul >

              <b><p id="hostAux{{ forloop.counter }}" class="listaDB{{ forloop.counter }}">{{artic.nombreDB}}</p></b>
              <li id="hostAux{{ forloop.counter }}" class="listaDB{{ forloop.counter }}">{{artic.host}}</li>
              <li id="userAux{{ forloop.counter }}" class="listaDB{{ forloop.counter }}">{{artic.user}}</li>
              <li id="passwordAux{{ forloop.counter }}" class="listaDB{{ forloop.counter }}" style="display: none">{{artic.password|safe}}</li>
              <li>*********</li>

            </ul>
            <button type="button" href="#contact" id='baseSave{{ forloop.counter }}'
              class='btnDB btn btn-dark btn-l text-uppercase'
              onclick="document.getElementById('contact').scrollIntoView();">seleccionar</button>


            <button type="button" href="#contact" id='baseDelete{{ forloop.counter }}'
              class='btnDB2 btn btn-dark btn-l text-uppercase' onclick="">eliminar</button><br><br><br>


        </div>
     
      <br><br>
      {%endfor%}
    </div>
    </div>
  </section>


  <section id="contact">







    <div class="container">



      <div class="row">




        <div class="col-lg-12 text-center">



          <h2 class="section-heading text-uppercase">Ingresa</h2>
          <h3 class="section-subheading text-muted">Introduce las credenciales de tu base de datos almacenada en neo4j.
          </h3>
        </div>
      </div>


      <div class="row">
        <div class="col-lg-12">

          <form action="{% url 'tesisForm:desarrollo' %}" method="post" id="formDB">
            {% csrf_token %}
            <div class="col-md-6 offset-md-3">
              {%for field in form2 %}

              <div class="form-group">
                {{field}}

              </div>


              {%endfor%}




              <div class="alert alert-danger alert-dismissible fade show" id="alertaTerminos" role="alert">
                <strong>IMPORTANTE!</strong> Para ingresar debes autorizar el acceso a tu base de datos.
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>





              <div class="checkbox">
                <input type="checkbox" value="Check Value" id="aceptoCT" readonly="readonly"
                  onclick="javascript: return false;" />
                <a href=# class="terms" data-toggle="modal" data-target="#myModal">Autorizar el acceso a la base de
                  datos</a>
              </div><br>
            </div>
            <div class="col-lg-12 text-center">
              <input type="submit" value="Validar" class="btn btn-primary btn-xl text-uppercase"
                onclick="validarAutenticacion();">
            </div>
          </form>
        </div>

      </div>






    </div>





    <!--  -->
    <div class="container">


      <!-- Modal Condiciones 2 -->
      <div class="modal fade" id="myModal" role="dialog" data-keyboard="false" data-backdrop="static">
        <div class="modal-dialog modal-ma">
          <div class="modal-content">
            <div class="modal-header">

              <h4 class="modal-title text-center">Condiciones de uso</h4>
            </div>
            <div class="modal-body text-justify">

              <p>Al ingresar tus bases de datos visualGraph analizará la información de ésta para extraer tipos de nodos
                y tipos de relaciones contenidas en la misma para casos de esquema gráfico y creación de interfaz
                interactiva. Además visualGraph
                almacena las credenciales de acceso con el fin de brindar una mejor experiencia al usuario con el
                compromiso de no hacer uso de los mismos.
              </p>
              <p>
                Las credenciales almacenadas se podrán eliminar en cualquier punto despues de su almacenamiento.</p>

              <strong>¿Acepta que visualGraph haga uso de su información?</strong>
            </div>
            <div class="modal-footer">
              <label><input type="checkbox" id="cbox1" value="first_checkbox"> Si, acepto</label><br>
              <button type="button" class="btn btn-default" data-dismiss="modal"
                onclick="checkTerms();">Confirmar</button>
            </div>
          </div>
        </div>
      </div>
    </div>


    <!-- Fin Modal Condiciones 2   -->





    <div id="mimodal" class="modal fade" role="dialog">
      <div class="modal-dialog">
        <span class="glyphicon glyphicon-ban-circle cerrar" data-dismiss="modal"></span>

        <img src="" class="modal-content recibir-imagen" width="80%" height="80%">

        <div class="modal-footer">
          <div class="col-lg-12 text-center">


          </div>
        </div>

      </div>
    </div>


  </section>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <span class="copyright">UCE &copy; Gmsc 2018</span>
        </div>
        <div class="col-md-4">
          <ul class="list-inline social-buttons">
            <li class="list-inline-item">
              <a href="#">
                <i class="fab fa-twitter"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <i class="fab fa-facebook-f"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <i class="fab fa-linkedin-in"></i>
              </a>
            </li>
          </ul>
        </div>


        <div class="col-md-4">
          <ul class="list-inline quicklinks">
            <li class="list-inline-item">
              <a href="#terminos_up" id="botonTer">Términos y condiciones
              </a>
            </li>

          </ul>
        </div>


      </div>
    </div>
  </footer>




  <!-- Bootstrap core JavaScript -->
  {% load static %}
  <script src="{% static 'tesisForm/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'tesisForm/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'tesisForm/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Contact form JavaScript -->
  <script src="{% static 'tesisForm/js/jqBootstrapValidation.js' %}"></script>
  <script src="{% static 'tesisForm/js/contact_me.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'tesisForm/js/agency.min.js' %}"></script>
  <script>



    
    $('a[href="#terminos_up"]').click(function () {

      $('.recibir-imagen').attr('src', 'http://canastahotel.com/wp-content/uploads/tc-icon.png');
      $('#mimodal').modal();
    });




    $('.btnDB').click(function () {
      var idAux = (this.id).match(/\d+/);
      //var hostT=$('#hostAux'+idAux).data('value');
      var nombreDBT = $(".listaDB" + idAux).eq(0).text();
      var hostT = $(".listaDB" + idAux).eq(1).text();
      var userT = $(".listaDB" + idAux).eq(2).text();
      var pwdT = $(".listaDB" + idAux).eq(3).text();
      //console.log(pwdT)
      $('#nombreDB').val(nombreDBT);
      $('#servidor').val(hostT);
      $('#database').val(userT);
      $('#pwd').val(pwdT);

    });



    $('.btnDB2').click(function (event) {
      var idAux = (this.id).match(/\d+/);
      var nombreDBT = $(".listaDB" + idAux).eq(0).text();
      var hostT = $(".listaDB" + idAux).eq(1).text();
      $(".UserDB" + idAux).hide();

      $.ajax({

        type: "POST",
        url: '{% url "tesisForm:prueba1" %}',
        data: {
          'csrfmiddlewaretoken': '{{ csrf_token }}',
          'nombreDBT': nombreDBT,
          'hostT': hostT

        },

      });

    });




    function checkTerms() {
      if ($('#cbox1').is(":checked")) {

        $('#aceptoCT').prop('checked', true);
        // it is checked
      } else {
        $('#aceptoCT').prop('checked', false);
      }


    }
    function validarAutenticacion() {
      if ($('#aceptoCT').is(":checked")) {


      } else {
        $("#formDB").submit(function (e) {
          e.preventDefault();

          location.reload();
          $('#alertaTerminos').alert();
        });

      }


    }




  </script>
</body>

</html>

Tesis_01/tesisForm/templates/tesisForm/signup.html
<!DOCTYPE html>
<html lang="es">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=0.7, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>visualGraph</title>

  <!-- Bootstrap core CSS -->
  {% load static %}
  <link href="{% static 'tesisForm/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->

  <link href="{% static 'tesisForm/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet'
    type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  {% load static %}
  <link href="{% static 'tesisForm/css/agency.min.css' %}" rel="stylesheet">


  {% load static %}
  <link href="{% static 'tesisForm/css/agency.min.css' %}" rel="stylesheet">



  <style>
    .formatoForm {
      color: aliceblue;
    }

    .etiquetaF {
      font-size: 30px;
      text-decoration: underline;
    }
  </style>
</head>

<body id="page-top">
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="{% url 'tesisForm:presentacion' %}">visualGraph</a>


      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
        data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
        aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>

    </div>
  </nav>




  <!-- Contact -->
  <section id="contact">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading text-uppercase">Formulario de registro</h2>
          <h3 class="section-subheading text-muted">Introduce los datos que se especifican para acceder a VisualGraph
          </h3>
        </div>
      </div>
      <div class="row formatoForm">
        <div class="col-lg-12">


          <form method="post">

            <div class="col-md-6 offset-md-3">
              {% csrf_token %}
         

              {% for field in form %} 
              
              <p class="text-center">{{ field.label }}</br>  {{ field}}</p>
              {% endfor %}
              <div class="col-lg-12 text-center">
                <input type="submit" value="Registrar" class="btn btn-danger btn-l text-uppercase">
              </div>
            </div>
          </form>
        </div>

      </div>

      <br><br><br>
   



    </div>
    </div>

    <div id="mimodal" class="modal fade" role="dialog">
      <div class="modal-dialog">
        <span class="glyphicon glyphicon-ban-circle cerrar" data-dismiss="modal"></span>

        <img src="" class="modal-content recibir-imagen" width="80%" height="80%">

        <div class="modal-footer">
          <div class="col-lg-12 text-center">


          </div>
        </div>

      </div>
    </div>
  </section>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <span class="copyright">UCE &copy; Gmsc 2018</span>
        </div>
        <div class="col-md-4">
          <ul class="list-inline social-buttons">
            <li class="list-inline-item">
              <a href="#">
                <i class="fab fa-twitter"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <i class="fab fa-facebook-f"></i>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <i class="fab fa-linkedin-in"></i>
              </a>
            </li>
          </ul>
        </div>


        <div class="col-md-4">
          <ul class="list-inline quicklinks">
            <li class="list-inline-item">
              <a href="#terminos_up" id="botonTer">Términos y condiciones
              </a>
            </li>

          </ul>
        </div>


      </div>
    </div>
  </footer>




  <!-- Bootstrap core JavaScript -->
  {% load static %}
  <script src="{% static 'tesisForm/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'tesisForm/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'tesisForm/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Contact form JavaScript -->
  <script src="{% static 'tesisForm/js/jqBootstrapValidation.js' %}"></script>
  <script src="{% static 'tesisForm/js/contact_me.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'tesisForm/js/agency.min.js' %}"></script>
  <script>
    $('a[href="#terminos_up"]').click(function () {

      $('.recibir-imagen').attr('src', 'http://canastahotel.com/wp-content/uploads/tc-icon.png');
      $('#mimodal').modal();
    }); 
  </script>
</body>

</html>